FZ83P-11
infoshareacademy/jfdz8-3-promile pull request #12
Opened 2018-04-11 05:07 UTC by bartzaw

I've added flex to add-info section along with mobile-first model. Added section container to better position all elements.

2018-04-11 05:16 UTC, sebastian-kreft requested changes
How is this PR different from this one: https://github.com/infoshareacademy/jfdz8-3-promile/pull/11

2018-04-11 18:41 UTC, icelandico approved these changes
Looks fine for me.

2018-04-13 04:59 UTC, bartzaw commented
hi @sebastian-kreft - this one relates to additional-info section, the one you've mentioned relates to features section. By mistake I've amended SOME of add-info styles in previous pull request, but this one you are reviewing now is suppose to change whole section to act as I'd like it to.

2018-04-15 11:32 UTC, Decomplosed approved these changes
All good!

2018-04-18 17:43 UTC, sebastian-kreft commented on assets/style/style.css
> +    font-size: 2rem;
I hope you know exactly how `rem` and `em` works and why you chose it :)

2018-04-18 17:46 UTC, sebastian-kreft approved these changes
It looks good. However, please be sure about using relative values for font sizes.

2018-04-18 18:38 UTC, merged