Fz83 p 5/hero
infoshareacademy/jfdz8-3-promile pull request #26
Opened 2018-04-27 20:19 UTC by Decomplosed

check how it works for now

2018-04-27 20:33 UTC, bartzaw requested changes
Please check out my comments, I

2018-04-27 20:33 UTC, bartzaw commented on assets/style/style.css
> +    width: 20rem;
this 'rem' thing, @sebastian-kreft  mentioned before that it shouldn't be used as a regular thing. Sebastian, can you elaborate? We can arrange call via slack with all 3 of us as it's not clear enough for me why it should not be used as often.

2018-04-27 20:33 UTC, bartzaw commented on assets/style/style.css
> +    color: black;
please use only colors using hex or rgb

2018-04-27 20:33 UTC, bartzaw commented on index.html
> +                    <h1>3VENT CITY - ENJOY 3CITY</h1>
Please do not use capital letters in html code, should be replaced by text-transform in css

2018-04-28 06:56 UTC, icelandico commented on assets/js/main.js
> +/*
I'm not sure leaving commented code is good idea?

2018-04-28 07:03 UTC, icelandico commented on assets/style/style.css
> +    width: 20rem;
Maybe for element width it's better to use `%` or `px`.

2018-04-28 07:05 UTC, icelandico approved these changes

2018-04-28 10:53 UTC, bartzaw approved these changes

2018-04-29 12:47 UTC, sebastian-kreft commented on assets/js/main.js
> +$('.carousel').carousel({
Don't leave such comments in the code, it's untidy :P

2018-04-30 08:25 UTC, merged