Fz83 p 9
infoshareacademy/jfdz8-3-promile pull request #27
Opened 2018-04-30 08:26 UTC by Decomplosed

Pls check the team info section

2018-04-30 15:50 UTC, bartzaw requested changes
Please see my comments to the code.

2018-04-30 15:50 UTC, bartzaw commented on assets/style/style.css
> +        flex-direction: row;
double flex-direction in this class? probably some left-over after merge

2018-04-30 15:50 UTC, bartzaw commented on assets/style/style.css
> +    opacity: 0;
why there's 0 opacity for container? Was it intended?

2018-04-30 15:50 UTC, bartzaw commented on assets/style/style.css
> +    opacity: 1;
and here's opacity: 1?

2018-04-30 16:15 UTC, icelandico commented on assets/style/style.css
> +    width: 80vw;
`vw` is a tricky unit. Shall look good but maybe `%` are better choice?

2018-04-30 16:18 UTC, icelandico commented on assets/style/style.css
> +    margin-bottom: 2em;
Suggestion: put margin styling in one line.

2018-04-30 16:19 UTC, icelandico approved these changes
Minor changes required.

2018-05-03 12:09 UTC, closed without merging

2018-05-03 12:10 UTC, Decomplosed commented
Closed this pull request - moved changes from team section to another branch