FZP83P-8_michalm
infoshareacademy/jfdz8-3-promile pull request #3
Opened 2018-03-25 12:05 UTC by icelandico

Please review!

2018-03-26 04:09 UTC, bartzaw commented
hi Michal, you need to add 'reviewers' in order for us to do 'review' ;)

2018-03-27 16:00 UTC, Decomplosed approved these changes
Seems good for me

2018-03-28 15:44 UTC, sebastian-kreft requested changes
There are conflicts that needs to be resolved before merge.

2018-03-28 15:44 UTC, sebastian-kreft commented on index.html
>          <section class="section" id="form">
`section` is not a good way od naiming classes. How would you name a class im another section elemen? `section-2`?

2018-03-28 15:44 UTC, sebastian-kreft commented on assets/style/style.css
> +.section#form {
Using id as a selector is a bad practice. It would be enough to use good names for classes. Remember that you can give more than one class to a single element.

2018-03-28 17:05 UTC, closed without merging