added changes to team section and more response on a smaller devices
infoshareacademy/jfdz8-3-promile pull request #34
Opened 2018-05-06 14:24 UTC by Decomplosed

take a look at those changes

2018-05-06 15:21 UTC, icelandico commented on assets/style/style.css
Maybe remove these wide whitespaces between selectors.

2018-05-06 15:22 UTC, icelandico commented on assets/style/style.css
> +@media (max-width:576px) {
If there's nothing more in this `media` query, it might be deleted.

2018-05-06 16:00 UTC, icelandico commented on assets/style/style.css
>  @media (max-width:1024px) {
Maybe use `max-width: 968px` for consistency in our style.css

2018-05-06 16:01 UTC, icelandico requested changes
Just minor changes or rather things to consider.

2018-05-06 16:58 UTC, bartzaw requested changes
please check out my comments

2018-05-06 16:58 UTC, bartzaw commented on assets/style/style.css
> +.fa-facebook-square:hover, .fa-linkedin:hover, .fa-instagram:hover, .fa-github-square:hover{
no need for facebook & instagram icons, please remove them. Moreover there's already hover for linkedin Icon in footer section, so you are going to have conflicting styles in here.

2018-05-06 16:58 UTC, bartzaw commented on assets/style/style.css
> +    padding-bottom: 20px;
padding: 20px 0; is what you are looking for here. No need to make it in separate lines

2018-05-06 16:58 UTC, bartzaw commented on assets/style/style.css
All icons have the same margin, why all of them are separate? + margin: 0 14px;

2018-05-06 17:18 UTC, Decomplosed commented on assets/style/style.css
> +.fa-facebook-square:hover, .fa-linkedin:hover, .fa-instagram:hover, .fa-github-square:hover{
facebook and instagram icons are removed from team-member, only added github to styles, so they would have exactly the same animation as icons in footer

2018-05-07 05:37 UTC, bartzaw commented on assets/style/style.css
> +.fa-facebook-square:hover, .fa-linkedin:hover, .fa-instagram:hover, .fa-github-square:hover{
got it! we can discuss it today

2018-05-07 18:50 UTC, closed without merging

2018-05-07 18:51 UTC, Decomplosed commented
pull request closed