FZ83P-6
infoshareacademy/jfdz8-3-promile pull request #4
Opened 2018-03-26 04:05 UTC by bartzaw

Hi folks, please check 1st version of featues section. Let me know if anything.

2018-03-27 15:58 UTC, Decomplosed approved these changes
seems fine to me

2018-03-28 16:55 UTC, icelandico commented on index.html
> -                <span>
Maybe it's better to nest <span> within <div>, not backwards?

2018-03-28 16:57 UTC, icelandico commented on assets/style/style.css
> +#add-info {
Following the suggestion of @sebastian-kreft on my request - We shall not use #id as a selector.

2018-03-28 17:00 UTC, icelandico requested changes
We should take account of @sebastian-kreft suggestions :)

2018-03-29 05:15 UTC, bartzaw commented
I removed those IDs as changes I've put in there were completely redundant.

2018-03-29 17:09 UTC, icelandico approved these changes
Great!

2018-03-29 17:34 UTC, merged