FZ83P9
infoshareacademy/jfdz8-3-promile pull request #8
Opened 2018-04-05 13:20 UTC by Decomplosed

Created basic team info section (will upgrade it); could you please check if it's fine for you right now, thanks!

2018-04-05 16:58 UTC, icelandico commented on index.html
> +                            <span class="fab fa-facebook"></span>
I'm not sure but font-awesome icons need to be nested inside another tag. So it shall be nested within another `span`.

2018-04-05 18:06 UTC, icelandico commented on assets/style/style.css
> +    z-index: 1;
Topbar has z-index value of 1. This section will overlap our navbar.

2018-04-05 18:09 UTC, icelandico requested changes
Just change z-index and span with font-awesome icons.

2018-04-05 19:10 UTC, Decomplosed commented on index.html
> +                            <span class="fab fa-facebook"></span>
Why is that? They are nested in div container with specified class. Any changes can be simply made by using that div and class of every span with font awesome icon

2018-04-05 19:12 UTC, Decomplosed commented on assets/style/style.css
> +    z-index: 1;
OK, got it

2018-04-05 19:22 UTC, Decomplosed commented on assets/style/style.css
> +    z-index: 1;
I just figured out it's a sction of @bartzaw . Should i change it? :D

2018-04-06 05:51 UTC, sebastian-kreft commented on assets/style/style.css
> +    flex: 1;
Do not use shorthand if you set only one value. Shorthands makes browser set all the values, even if you typed only one. This is like writing 3 declarations but with default values. Better to use `flex-grow: 1`

2018-04-06 05:53 UTC, sebastian-kreft commented on assets/style/style.css
> +/* http://meyerweb.com/eric/tools/css/reset/
Reset declaration should be in a separate file `reset.css`

2018-04-06 05:54 UTC, sebastian-kreft reviewed
See my comments. Other than that it looks fine.

2018-04-08 05:54 UTC, bartzaw commented on index.html
> +                            <span class="fab fa-facebook"></span>
these are fine, there cannot be anything between those span tags and it's not the case. If spans are nested inside of div it will be working as a charm. Tried it myself

2018-04-08 05:58 UTC, bartzaw commented on assets/style/style.css
> +    z-index: 1;
sorry, which section? I don't see anything in your code related to my sections. May be wrong though!

2018-04-10 04:53 UTC, bartzaw approved these changes
reviewing team section - looks good to me

2018-04-10 20:35 UTC, icelandico approved these changes
It's ok for me now.

2018-04-11 05:15 UTC, sebastian-kreft commented
You have to resolve conflicts on this branch before merging it.

2018-04-11 05:15 UTC, sebastian-kreft approved these changes

2018-04-11 14:56 UTC, merged